// <auto-generated />
namespace TourismApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Categorie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categorie));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051623035_Categorie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
